version: '3'
services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - API_Domain=http://192.168.99.100:3001
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
