api:
  port: 3001

db:
  name: dewi
  local:
    host: localhost
    port: 27017
  docker:
    image: mongo
  options:
    useNewUrlParser: true
    useFindAndModify: false
    useCreateIndex: true
    useUnifiedTopology: true
    autoReconnect: true

weather:
  dwd:
    wfs:
      url:
        protocol: https
        hostname: maps.dwd.de
        path: /geoserver/dwd/ows
      parameter:
        version: 2.0.0
        typeName: dwd:Warnungen_Gemeinden_vereinigt
        filter:
          # @see pp.17 https://www.dwd.de/DE/wetter/warnungen_aktuell/objekt_einbindung/einbindung_karten_geowebservice.pdf?__blob=publicationFile&v=11
          severity:
            moderate: true # TODO
            minor: true  # TODO
            severe: false # TODO
            extreme: false # TODO
      # in seconds
      refreshIntervall: 30


social:
  twitter:
    api:
      url:
        protocol: https
        #hostname: api.twitter.com
        path: /oauth2/token
    token:
      consumerKey: # TODO
      consumerSecret: # TODO 
    # in seconds
    storageDuration: 3600


notification:
  email:
    from:
      adress: dewi_service@gmx.de
      password: # TODO
    to:
      sender: \"DEWI\" <dewi_service@gmx.de>
      receiver: dewi_service@gmx.de
    options:
      host: mail.gmx.net
      port: 587
      secure: false
      tls:
        rejectUnauthorized: false
  mattermost:
    url:
      parameter:
        yourMattermostSite: zivmattermost.uni-muenster.de
        generatedHookKey: qmpo3bj8u3ff7p8corfncqkbrr
        # Hook for the DEWI-Team: m9oghpjxztfybjatsrmw4u437e
        # Hook for the GeoSoft2-Team: qmpo3bj8u3ff7p8corfncqkbrr
